// Sample configuration shown by the HAProxy editor in demo mode.
export const DEMO_HAPROXY_CONFIG = `# Generated by NodeFlow. Do not edit.
# renderer: haproxy-tcp-sni-v21

global
    maxconn 20000
    log /dev/log local0
    log /dev/log local1 notice
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    tune.pipesize 262144
    localpeer nf_local

defaults
    log global
    mode tcp
    option tcplog
    option dontlognull
    option clitcpka
    option srvtcpka
    .if enabled(SPLICE)
        option splice-request
        option splice-response
    .endif
    timeout connect 5s
    timeout client 15m
    timeout server 15m

peers nf_peers
    bind unix@/run/haproxy/nf_peers.sock
    server nf_local

frontend nf_fe_any_443_1a2b3c4d
    bind :443
    mode tcp
    option tcplog
    tcp-request inspect-delay 5s
    tcp-request content accept if { req.ssl_hello_type 1 }
    acl nf_sni_7f3e req.ssl_sni -i vpn.example.com
    use_backend nf_be_7f3e if nf_sni_7f3e
    default_backend nf_be_91aa

backend nf_be_7f3e
    mode tcp
    # nodeflow route_id=7f3e0000-0000-0000-0000-000000000001
    balance leastconn
    option redispatch
    server nf_srv_7f3e 192.0.2.10:443 check inter 5s fall 3 rise 2 send-proxy-v2 check-send-proxy

backend nf_be_91aa
    mode tcp
    # nodeflow route_id=91aa0000-0000-0000-0000-000000000002
    server nf_srv_91aa 192.0.2.20:8443 check inter 5s fall 3 rise 2
`;
