package panel

import (
	"compress/gzip"
	"encoding/json"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
)

// uiRoutePayloadCase is one request body produced by the route editor's
// routePayload() for a draft the editor itself accepts (see
// frontend/tests/routeMatrix.ts, fixture regenerated by
// UPDATE_UI_FIXTURES=1 npm test in frontend/).
type uiRoutePayloadCase struct {
	Name    string          `json:"name"`
	Method  string          `json:"method"`
	Payload json.RawMessage `json:"payload"`
	Stored  *Route          `json:"stored"`
}

// knownStickyNoneFlat is the flat (single-target) sticky_mode "none" bug
// (resolveStickyMode), owned by another change.
// known: fixed in fix-sticky
const knownStickyNoneFlat = "sticky_mode must be source, source_table, leastconn or roundrobin"

// knownRoundTripDiffs are loaded routes whose re-save changes the config.
var knownRoundTripDiffs = map[string]string{
	// The editor sends sticky_mode "none" for a single target, dropping the
	// stored flat balance line. known: fixed in fix-sticky
	"loaded/flat pre-051 sticky_enabled/save": "flat sticky_mode none",
	"loaded/flat leastconn legacy/save":       "flat sticky_mode none",
	"loaded/flat source/save":                 "flat sticky_mode none",
	"loaded/flat source_table/save":           "flat sticky_mode none",
	// Deliberate: «Меньше соединений» folds stored costs into integer
	// weights on load (leastconnFold.ts), which re-rounds the weights.
	"loaded/servers leastconn costs/save": "leastconn cost fold",
}

// TestUIRoutePayloadsPassBackendValidation is the frontend↔backend route
// contract: every payload the editor can send for a draft it accepts must pass
// validateRoute, and the validated route must render (the renderer
// re-validates stored intent, so a value accepted on save must not break the
// node config later).
func TestUIRoutePayloadsPassBackendValidation(t *testing.T) {
	file, err := os.Open("testdata/ui_route_payloads.json.gz")
	require.NoError(t, err)
	defer file.Close()
	reader, err := gzip.NewReader(file)
	require.NoError(t, err)
	var cases []uiRoutePayloadCase
	require.NoError(t, json.NewDecoder(reader).Decode(&cases))
	require.Greater(t, len(cases), 4000, "fixture unexpectedly small")

	known := 0
	for _, c := range cases {
		in := decodeRouteInput(t, string(c.Payload))
		if c.Method == "PUT" && c.Stored != nil {
			present, err := routeInputKeys(c.Payload)
			require.NoError(t, err, c.Name)
			if routeInputOmitsStoredFields(present) {
				mergeAbsentRouteFields(&in, present, *c.Stored)
			}
		}
		spec, err := validateRoute(in, c.Method == "PUT")
		// Single plain servers and a lone DNS-pool server are folded into the
		// flat path, where resolveStickyMode rejects "none".
		if err != nil && err.Error() == knownStickyNoneFlat && in.StickyMode == "none" {
			known++ // known: fixed in fix-sticky
			continue
		}
		if err != nil {
			t.Errorf("%s: UI payload rejected by validateRoute: %v\npayload: %s", c.Name, err, c.Payload)
			continue
		}
		got, err := RenderHAProxyConfig([]Route{specToRoute(spec)})
		if err != nil {
			t.Errorf("%s: UI payload accepted but does not render: %v", c.Name, err)
			continue
		}
		if c.Stored == nil {
			continue
		}
		// An existing route opened in the editor and saved unchanged must keep
		// its HAProxy config byte for byte.
		stored := *c.Stored
		stored.ID, stored.Enabled = reviewRouteID, true
		want, err := RenderHAProxyConfig([]Route{stored})
		require.NoError(t, err, c.Name)
		if reason, ok := knownRoundTripDiffs[c.Name]; ok {
			require.NotEqual(t, want.Config, got.Config, "%s no longer differs (%s): drop it from knownRoundTripDiffs", c.Name, reason)
			continue
		}
		require.Equal(t, backendSection(want.Config), backendSection(got.Config), c.Name)
		require.Equal(t, want.Config, got.Config, c.Name)
	}
	t.Logf("%d UI payloads checked, %d skipped as known flat sticky_mode=none", len(cases), known)
}
