package panel

import (
	"fmt"
	"math"
	"net"
	"path"
	"sort"
	"strings"
	"unicode/utf8"
)

const (
	defaultRouteListenerIP   = "*"
	defaultRouteListenerPort = 443
	defaultRouteMatchMode    = "sni"
	defaultRouteTargetType   = "tcp"
	defaultProxyProtocol     = "none"
	defaultQuotaAction       = "observe"
	defaultQuotaPeriod       = "calendar_month"
	// HAProxy byte-rate values are generated by multiplying Mbps by 125000.
	// This permits per-client rates through 1 Tbps while keeping generated
	// values well within HAProxy's integer rate parser.
	maxRouteClientRateMbps int64 = 1_000_000
)

type routeInput struct {
	ExpectedVersion *int64 `json:"expected_version"`
	Name            string `json:"name"`
	// Hostname is the legacy single-SNI field. New clients should use SNIs.
	Hostname           string             `json:"hostname"`
	ListenerIP         string             `json:"listener_ip"`
	ListenerPort       *int               `json:"listener_port"`
	MatchMode          string             `json:"match_mode"`
	SNIs               []string           `json:"snis"`
	Fallback           bool               `json:"fallback"`
	TargetType         string             `json:"target_type"`
	TargetHost         string             `json:"target_host"`
	TargetPort         int                `json:"target_port"`
	DNSPool            bool               `json:"dns_pool"`
	UnixSocketPath     string             `json:"unix_socket_path"`
	HealthCheck        *bool              `json:"health_check"`
	ProxyProtocol      string             `json:"proxy_protocol"`
	AcceptProxyFrom    []string           `json:"accept_proxy_from"`
	QuotaBytes         *int64             `json:"quota_bytes"`
	QuotaAction        string             `json:"quota_action"`
	QuotaPeriod        string             `json:"quota_period"`
	ClientUploadMbps   *int64             `json:"client_upload_mbps"`
	ClientDownloadMbps *int64             `json:"client_download_mbps"`
	Enabled            *bool              `json:"enabled"`
	CustomFragment     string             `json:"custom_fragment"`
	Servers            []routeServerInput `json:"servers"`
	StickyEnabled      bool               `json:"sticky_enabled"`
	// BalanceMode empty means "absent": explicit servers[].backup flags are
	// then kept as sent (1.1.0-rc API compatibility).
	BalanceMode string `json:"balance_mode"`
	ShaperMode  string `json:"shaper_mode"`
	// StickyMode empty means "absent": it is derived from sticky_enabled and
	// DNS pools (see resolveStickyMode). When present it wins over
	// sticky_enabled.
	StickyMode string `json:"sticky_mode"`
	StickyTTL  string `json:"sticky_ttl"`
	// Deprecated since migration 000030 (sticky uses a consistent source
	// hash, no stick-table). Accepted and ignored so rc-era clients and
	// cached SPA bundles are not rejected by DisallowUnknownFields.
	StickyTableSize *string `json:"sticky_table_size,omitempty"`
	StickyExpire    *string `json:"sticky_expire,omitempty"`
	// Migration 000052: balance_algorithm (server choice) and sticky_mode
	// (client stickiness) are two orthogonal pool-mode settings. See
	// resolvePoolDistribution.
	BalanceAlgorithm   string   `json:"balance_algorithm"`
	BalanceRandomDraws int      `json:"balance_random_draws"`
	LeastPingTolerance *float64 `json:"leastping_tolerance"`
	// BalanceTolerance is the algorithm-neutral name of leastping_tolerance
	// (it also drives leastconn). Either key may be sent; when both are
	// present they must agree.
	BalanceTolerance        *float64 `json:"balance_tolerance"`
	LeastPingToleranceMS    int      `json:"leastping_tolerance_ms"`
	StickyHash              string   `json:"sticky_hash"`
	StickyHashBalanceFactor int      `json:"sticky_hash_balance_factor"`
	StickyTableEntries      string   `json:"sticky_table_entries"`
	StickyIPv6Prefix        int      `json:"sticky_ipv6_prefix"`
	// ClientIPv6 (migration 000054): nil means true on create and the
	// stored value on a partial PUT (see mergeAbsentRouteFields).
	ClientIPv6 *bool  `json:"client_ipv6"`
	Slowstart  string `json:"slowstart"`
}

type routeServerInput struct {
	Position       int    `json:"position"`
	Name           string `json:"name"`
	TargetType     string `json:"target_type"`
	Host           string `json:"host"`
	Port           int    `json:"port"`
	UnixSocketPath string `json:"unix_socket_path"`
	Backup         bool   `json:"backup"`
	DNSPool        bool   `json:"dns_pool"`
	PreferredIP    string `json:"preferred_ip"`
	// Migration 000052.
	Weight    int                   `json:"weight"`
	Cost      float64               `json:"cost"`
	IPWeights []RouteServerIPWeight `json:"ip_weights"`
}

func validateRoute(in routeInput, requireEnabled bool) (RouteSpec, error) {
	var out RouteSpec
	if in.ExpectedVersion != nil {
		if *in.ExpectedVersion < 1 {
			return out, fmt.Errorf("expected_version must be a positive integer")
		}
		version := *in.ExpectedVersion
		out.ExpectedVersion = &version
	}

	if containsForbiddenControl(in.Name) || containsForbiddenControl(in.ListenerIP) ||
		containsForbiddenControl(in.MatchMode) || containsForbiddenControl(in.TargetType) ||
		containsForbiddenControl(in.TargetHost) || containsForbiddenControl(in.UnixSocketPath) ||
		containsForbiddenControl(in.ProxyProtocol) || containsForbiddenControl(in.QuotaAction) ||
		containsForbiddenControl(in.QuotaPeriod) {
		return out, fmt.Errorf("route fields cannot contain control characters")
	}
	listenerIP := strings.TrimSpace(in.ListenerIP)
	if listenerIP == "" {
		listenerIP = defaultRouteListenerIP
	}
	if listenerIP != defaultRouteListenerIP {
		ip := net.ParseIP(listenerIP)
		if ip == nil {
			return out, fmt.Errorf("listener_ip must be * or an IP address")
		}
		listenerIP = ip.String()
	}
	listenerPort := defaultRouteListenerPort
	if in.ListenerPort != nil {
		listenerPort = *in.ListenerPort
	}
	if listenerPort < 1 || listenerPort > 65535 {
		return out, fmt.Errorf("listener_port must be between 1 and 65535")
	}
	out.ListenerIP, out.ListenerPort = listenerIP, listenerPort

	matchMode := strings.ToLower(strings.TrimSpace(in.MatchMode))
	if matchMode == "" {
		matchMode = defaultRouteMatchMode
		if in.Fallback {
			if wildcardListenerIP(listenerIP) {
				matchMode = "fallback"
			} else {
				matchMode = "fallback"
			}
		}
	}
	// Normalize legacy values: any_tcp and destination_ip map to fallback.
	// The distinction is preserved in listener_ip (wildcard vs concrete).
	if matchMode == "any_tcp" || matchMode == "destination_ip" {
		matchMode = "fallback"
	}
	if matchMode != "fallback" && matchMode != "sni" {
		return out, fmt.Errorf("match_mode must be sni or fallback (any_tcp and destination_ip are deprecated aliases for fallback)")
	}
	if matchMode == "fallback" && wildcardListenerIP(listenerIP) {
		// wildcard + fallback is the successor to any_tcp — valid
	} else if matchMode == "fallback" && !wildcardListenerIP(listenerIP) {
		// concrete IP + fallback is the successor to destination_ip — valid
	}
	// Legacy compat checks removed; wildcard/concrete distinction is on listener_ip.
	out.MatchMode = matchMode

	legacyHostname := ""
	if strings.TrimSpace(in.Hostname) != "" {
		var ok bool
		legacyHostname, ok = normalizeDNSName(in.Hostname)
		if !ok {
			return out, fmt.Errorf("hostname must be a valid DNS name")
		}
	}
	if len(in.SNIs) > MaxRouteSNIs {
		return RouteSpec{}, fmt.Errorf("no more than %d SNI values are allowed", MaxRouteSNIs)
	}
	seen := make(map[string]struct{}, len(in.SNIs))
	for _, value := range in.SNIs {
		sni, ok := normalizeDNSName(value)
		if !ok {
			return out, fmt.Errorf("every SNI must be a valid DNS name")
		}
		if _, exists := seen[sni]; exists {
			return out, fmt.Errorf("SNI values must be unique")
		}
		seen[sni] = struct{}{}
		out.SNIs = append(out.SNIs, sni)
	}
	if len(out.SNIs) == 0 && legacyHostname != "" {
		out.SNIs = []string{legacyHostname}
	} else if legacyHostname != "" && out.SNIs[0] != legacyHostname {
		return RouteSpec{}, fmt.Errorf("hostname must equal the first SNI when both are provided")
	}
	if matchMode != "sni" {
		if len(out.SNIs) != 0 || legacyHostname != "" {
			return RouteSpec{}, fmt.Errorf("match_mode %s cannot contain SNI values", matchMode)
		}
		out.SNIs = []string{}
		out.Fallback = true
	} else {
		if in.Fallback {
			return RouteSpec{}, fmt.Errorf("match_mode sni cannot be fallback")
		}
		if len(out.SNIs) == 0 {
			return RouteSpec{}, fmt.Errorf("match_mode sni requires at least one SNI")
		}
	}
	if len(out.SNIs) > 0 {
		out.Hostname = out.SNIs[0]
	}

	name := strings.TrimSpace(in.Name)
	if name == "" {
		switch matchMode {
		case "sni":
			name = out.Hostname
		case "fallback":
			if wildcardListenerIP(listenerIP) {
				name = "tcp-" + fmt.Sprint(listenerPort)
			} else {
				name = "ip-" + listenerIP + "-" + fmt.Sprint(listenerPort)
			}
		default:
			name = "tcp-" + fmt.Sprint(listenerPort)
		}
	}
	if utf8.RuneCountInString(name) < 1 || utf8.RuneCountInString(name) > 80 {
		return RouteSpec{}, fmt.Errorf("name must contain between 1 and 80 characters")
	}
	out.Name = name

	// servers[] is the source of truth whenever it is supplied. The legacy
	// single-target fields (and route-level dns_pool) are derived from it.
	servers, balanceMode, err := resolveRouteServers(in.Servers, in.BalanceMode)
	if err != nil {
		return RouteSpec{}, err
	}
	if len(in.Servers) > 0 {
		// Route-level dns_pool is legacy-only for routes without servers: a
		// client that sets it together with servers[] (the 1.1.0 editor does
		// when any server is a DNS pool) must not switch the renderer to the
		// legacy single-template path and silently drop the other servers.
		in.DNSPool = false
		primary := servers[0]
		for _, s := range servers {
			if !s.Backup {
				primary = s
				break
			}
		}
		in.TargetType = primary.TargetType
		in.TargetHost, in.TargetPort, in.UnixSocketPath = primary.Host, primary.Port, primary.UnixSocketPath
		if len(servers) == 1 && primary.PreferredIP == "" && primary.Weight == 0 && primary.Cost == 0 && len(primary.IPWeights) == 0 &&
			!(primary.DNSPool && poolDistributionNeedsServers(in)) {
			// A single server without preferred_ip, weight, cost or
			// ip_weights is exactly the legacy single-target route. Store it
			// that way so the backend keeps the canonical nf_srv_<id> server
			// (quota block_new and runtime names depend on it) and the render
			// stays byte-identical to routes created before servers[]
			// existed. routes has no weight/cost/ip_weights columns of its
			// own, so a server that sets any of them must stay explicit.
			// A single DNS pool balances between its addresses: when the
			// client asks for a tolerance or an algorithm the legacy path
			// cannot express, it stays a servers[] route so the setting is
			// kept instead of being silently dropped.
			in.DNSPool = primary.DNSPool
			servers = nil
		}
	}

	targetType := strings.ToLower(strings.TrimSpace(in.TargetType))
	if targetType == "" {
		targetType = defaultRouteTargetType
	}
	out.TargetType = targetType
	switch targetType {
	case "tcp":
		if strings.TrimSpace(in.UnixSocketPath) != "" {
			return RouteSpec{}, fmt.Errorf("unix_socket_path is only valid for unix targets")
		}
		host, ok := normalizeTargetHost(in.TargetHost)
		if !ok || in.TargetPort < 1 || in.TargetPort > 65535 {
			return RouteSpec{}, fmt.Errorf("TCP target requires a valid target_host and target_port")
		}
		out.TargetHost, out.TargetPort = host, in.TargetPort
		out.DNSPool = in.DNSPool
		if out.DNSPool && net.ParseIP(host) != nil {
			return RouteSpec{}, fmt.Errorf("dns_pool requires a DNS target_host")
		}
	case "unix":
		if in.DNSPool {
			return RouteSpec{}, fmt.Errorf("dns_pool is only valid for DNS targets")
		}
		if strings.TrimSpace(in.TargetHost) != "" || in.TargetPort != 0 {
			return RouteSpec{}, fmt.Errorf("unix target cannot contain target_host or target_port")
		}
		socketPath := strings.TrimSpace(in.UnixSocketPath)
		if !validUnixSocketPath(socketPath) {
			return RouteSpec{}, fmt.Errorf("unix_socket_path must be a canonical absolute Linux socket path up to %d bytes", MaxUnixSocketPathBytes)
		}
		out.UnixSocketPath = socketPath
	default:
		return RouteSpec{}, fmt.Errorf("target_type must be tcp or unix")
	}
	out.HealthCheck = true
	if in.HealthCheck != nil {
		out.HealthCheck = *in.HealthCheck
	}
	if out.DNSPool {
		out.HealthCheck = true
	}

	proxyProtocol := strings.ToLower(strings.TrimSpace(in.ProxyProtocol))
	if proxyProtocol == "" {
		proxyProtocol = defaultProxyProtocol
	}
	if proxyProtocol != "none" && proxyProtocol != "v1" && proxyProtocol != "v2" {
		return RouteSpec{}, fmt.Errorf("proxy_protocol must be none, v1 or v2")
	}
	out.ProxyProtocol = proxyProtocol
	acceptProxyFrom, err := validateAcceptProxyFrom(in.AcceptProxyFrom)
	if err != nil {
		return RouteSpec{}, err
	}
	out.AcceptProxyFrom = acceptProxyFrom
	if in.QuotaBytes != nil {
		if *in.QuotaBytes <= 0 {
			return RouteSpec{}, fmt.Errorf("quota_bytes must be a positive integer or null")
		}
		quota := *in.QuotaBytes
		out.QuotaBytes = &quota
	}
	quotaAction := strings.ToLower(strings.TrimSpace(in.QuotaAction))
	if quotaAction == "" {
		quotaAction = defaultQuotaAction
	}
	if quotaAction != "observe" && quotaAction != "block_new" {
		return RouteSpec{}, fmt.Errorf("quota_action must be observe or block_new")
	}
	if quotaAction == "block_new" && out.QuotaBytes == nil {
		return RouteSpec{}, fmt.Errorf("quota_action block_new requires quota_bytes")
	}
	if quotaAction == "block_new" && out.DNSPool {
		return RouteSpec{}, fmt.Errorf("quota_action block_new is not supported with dns_pool")
	}
	out.QuotaAction = quotaAction
	quotaPeriod := strings.ToLower(strings.TrimSpace(in.QuotaPeriod))
	if quotaPeriod == "" {
		quotaPeriod = defaultQuotaPeriod
	}
	if !validQuotaPeriod(quotaPeriod) {
		return RouteSpec{}, fmt.Errorf("quota_period must be hourly, daily, calendar_month or monthly_from_creation")
	}
	out.QuotaPeriod = quotaPeriod
	clientUploadMbps, err := validateClientRateMbps(in.ClientUploadMbps, "client_upload_mbps")
	if err != nil {
		return RouteSpec{}, err
	}
	out.ClientUploadMbps = clientUploadMbps
	clientDownloadMbps, err := validateClientRateMbps(in.ClientDownloadMbps, "client_download_mbps")
	if err != nil {
		return RouteSpec{}, err
	}
	out.ClientDownloadMbps = clientDownloadMbps
	if requireEnabled && in.Enabled == nil {
		return RouteSpec{}, fmt.Errorf("enabled is required")
	}
	out.Enabled = true
	if in.Enabled != nil {
		out.Enabled = *in.Enabled
	}
	customFragment, err := normalizeCustomFragment(in.CustomFragment)
	if err != nil {
		return RouteSpec{}, err
	}
	if (out.DNSPool || anyServerDNSPool(servers)) && dnsPoolFragmentConflict(customFragment) {
		return RouteSpec{}, fmt.Errorf("custom_fragment cannot override DNS pool server or balancing directives")
	}
	out.CustomFragment = customFragment
	if len(servers) > 0 && quotaAction == "block_new" {
		// Runtime block_new disables the single nf_srv_<id> server through the
		// HAProxy Runtime API; a multi-server backend has no such server.
		return RouteSpec{}, fmt.Errorf("quota_action block_new is not supported with multiple servers")
	}
	if anyServerDNSPool(servers) {
		// DNS-pool templates depend on health checks to drop dead addresses,
		// exactly like the legacy route-level dns_pool.
		out.HealthCheck = true
	}
	out.Servers = servers
	if len(servers) == 0 {
		// Single-target routes have nothing to balance between.
		balanceMode = "pool"
	}
	out.BalanceMode = balanceMode
	shaperMode, err := normalizeShaperMode(in.ShaperMode)
	if err != nil {
		return RouteSpec{}, err
	}
	out.ShaperMode = shaperMode
	// client_ipv6 (absent = true) applies to every client table of the
	// route: the source_table stick-table, the source hash and the HAProxy
	// bandwidth limiter.
	out.ClientIPv4Only = in.ClientIPv6 != nil && !*in.ClientIPv6
	if len(out.Servers) == 0 {
		// Single-target routes have nothing to balance between: keep the
		// pre-052 flat sticky_mode derivation and store algorithm ''.
		stickyMode, stickyTTL, err := resolveStickyMode(in, out, balanceMode)
		if err != nil {
			return RouteSpec{}, err
		}
		out.StickyMode, out.StickyTTL = stickyMode, stickyTTL
		// sticky_enabled stays in the API and fingerprint for compatibility: it
		// is true exactly when the client address pins the server.
		out.StickyEnabled = stickyMode == StickyModeSource || stickyMode == StickyModeSourceTable
		slowstart, err := validateSlowstart(in.Slowstart, out.HealthCheck)
		if err != nil {
			return RouteSpec{}, err
		}
		out.Slowstart = slowstart
		return out, nil
	}
	if err := resolvePoolDistribution(&in, &out, balanceMode); err != nil {
		return RouteSpec{}, err
	}
	return out, nil
}

const (
	StickyModeNone        = "none"
	StickyModeSource      = "source"
	StickyModeSourceTable = "source_table"
	// StickyModeLeastConn and StickyModeRoundRobin are legacy sticky_mode
	// input values (pre-000052): still accepted on input for single-target
	// routes and, for pool routes, mapped into balance_algorithm by
	// resolvePoolDistribution. Never stored as sticky_mode by fresh writes.
	StickyModeLeastConn  = "leastconn"
	StickyModeRoundRobin = "roundrobin"
	// StickyModeSNI is a removed sticky_mode value (migration 000052): the
	// render path is gone and the value is rejected on input. Rows written
	// before the removal may still carry it in the database (CHECK keeps it
	// for safety) and render as unset.
	StickyModeSNI       = "sni"
	stickyModeSNIError  = "sticky_mode sni was removed: it balances whole domains, not clients; use source or source_table"
	defaultStickyTTL    = "1h"
	minStickyTTLSeconds = 60
	maxStickyTTLSeconds = 7 * 24 * 3600
)

func validStickyMode(mode string) bool {
	switch mode {
	case StickyModeSource, StickyModeSourceTable, StickyModeLeastConn, StickyModeRoundRobin:
		return true
	}
	return false
}

// resolveStickyMode settles the client distribution of a single-target route
// (no servers[]): the pre-000052 flat model, unchanged. An absent sticky_mode
// is derived from the pre-000051 fields: sticky_enabled or any DNS pool means
// a source hash (DNS pools were always source-hash sticky in 1.0.8), anything
// else round robin. Failover keeps strict priority order, so the mode is
// validated but stored empty and renders nothing.
func resolveStickyMode(in routeInput, out RouteSpec, balanceMode string) (string, string, error) {
	if containsForbiddenControl(in.StickyMode) || containsForbiddenControl(in.StickyTTL) {
		return "", "", fmt.Errorf("route fields cannot contain control characters")
	}
	mode := strings.ToLower(strings.TrimSpace(in.StickyMode))
	if mode == StickyModeSNI {
		return "", "", fmt.Errorf(stickyModeSNIError)
	}
	if mode == "" {
		switch {
		case in.StickyEnabled, out.DNSPool, anyServerDNSPool(out.Servers):
			mode = StickyModeSource
		default:
			mode = StickyModeRoundRobin
		}
	}
	if !validStickyMode(mode) {
		return "", "", fmt.Errorf("sticky_mode must be source, source_table, leastconn or roundrobin")
	}
	ttl := strings.ToLower(strings.TrimSpace(in.StickyTTL))
	if ttl != "" {
		if _, ok := parseStickyTTL(ttl); !ok {
			return "", "", fmt.Errorf("sticky_ttl must be an HAProxy time between 1m and 7d (for example 15m, 1h, 7d)")
		}
	}
	if balanceMode == "failover" {
		return "", "", nil
	}
	if mode != StickyModeSourceTable {
		return mode, "", nil
	}
	if ttl == "" {
		ttl = defaultStickyTTL
	}
	return mode, ttl, nil
}

// parseStickyTTL accepts a positive integer with an s/m/h/d unit (the subset
// of HAProxy time syntax the UI offers) within 1m..7d.
func parseStickyTTL(value string) (int64, bool) {
	if len(value) < 2 || len(value) > 8 {
		return 0, false
	}
	unit := value[len(value)-1]
	digits := value[:len(value)-1]
	var n int64
	for _, char := range digits {
		if char < '0' || char > '9' {
			return 0, false
		}
		n = n*10 + int64(char-'0')
	}
	if digits[0] == '0' {
		return 0, false
	}
	var seconds int64
	switch unit {
	case 's':
		seconds = n
	case 'm':
		seconds = n * 60
	case 'h':
		seconds = n * 3600
	case 'd':
		seconds = n * 86400
	default:
		return 0, false
	}
	if seconds < minStickyTTLSeconds || seconds > maxStickyTTLSeconds {
		return 0, false
	}
	return seconds, true
}

func anyServerDNSPool(servers []RouteServerSpec) bool {
	for _, s := range servers {
		if s.DNSPool {
			return true
		}
	}
	return false
}

// Balancing algorithm choices (migration 000052). BalanceAlgorithmRoundRobin
// and "" both render nothing (HAProxy default); a stored route only ever
// carries the empty string for a single-target route (nothing to balance
// between).
const (
	BalanceAlgorithmRoundRobin = "roundrobin"
	BalanceAlgorithmStaticRR   = "static-rr"
	BalanceAlgorithmRandom     = "random"
	BalanceAlgorithmLeastConn  = "leastconn"
	BalanceAlgorithmLeastPing  = "leastping"

	minBalanceRandomDraws      = 1
	maxBalanceRandomDraws      = 5
	defaultBalanceRandomDraws  = 2
	defaultLeastPingTolerance  = 0.2
	maxLeastPingToleranceMS    = 1000
	minStickyHashBalanceFactor = 101
	maxStickyHashBalanceFactor = 1000
	minStickyIPv6Prefix        = 32
	maxStickyIPv6Prefix        = 128
	defaultStickyIPv6Prefix    = 64
	minSlowstartSeconds        = 1
	maxSlowstartSeconds        = 600
)

// poolDistributionNeedsServers reports whether the requested distribution
// of a single-server route can only be expressed on the servers[] path:
// a leastconn tolerance, leastping, random, static-rr or an algorithm other
// than the one the legacy single-target render implies. With sticky_mode
// source the algorithm and tolerance are inert, so nothing is lost there.
func poolDistributionNeedsServers(in routeInput) bool {
	sticky := strings.ToLower(strings.TrimSpace(in.StickyMode))
	if sticky == StickyModeSource || sticky == "" {
		// '' on a DNS pool resolves to source (see resolvePoolDistribution):
		// the source hash ignores algorithm and tolerance.
		return false
	}
	tolerance := 0.0
	if in.LeastPingTolerance != nil {
		tolerance = *in.LeastPingTolerance
	}
	if in.BalanceTolerance != nil {
		tolerance = *in.BalanceTolerance
	}
	if tolerance > 0 || in.LeastPingToleranceMS > 0 {
		return true
	}
	algorithm := strings.ToLower(strings.TrimSpace(in.BalanceAlgorithm))
	switch sticky {
	case StickyModeLeastConn:
		sticky, algorithm = StickyModeNone, BalanceAlgorithmLeastConn
	case StickyModeRoundRobin:
		sticky, algorithm = StickyModeNone, BalanceAlgorithmRoundRobin
	}
	if algorithm == "" {
		return false
	}
	legacyDefault := BalanceAlgorithmRoundRobin
	if sticky == StickyModeSourceTable {
		legacyDefault = BalanceAlgorithmLeastConn
	}
	return algorithm != legacyDefault
}

func validBalanceAlgorithm(value string) bool {
	switch value {
	case "", BalanceAlgorithmRoundRobin, BalanceAlgorithmStaticRR, BalanceAlgorithmRandom, BalanceAlgorithmLeastConn, BalanceAlgorithmLeastPing:
		return true
	}
	return false
}

// Stick-table size bounds (migration 000053): <n>k with n 1..10000 or <n>m
// with n 1..10 (HAProxy k/m suffixes, 2^10/2^20 entries). The old presets
// 10k/100k/1m stay valid and render byte-identically.
const (
	maxStickyTableEntriesK = 10000
	maxStickyTableEntriesM = 10
)

func validStickyTableEntries(value string) bool {
	if value == "" {
		return true
	}
	if len(value) < 2 || len(value) > 6 {
		return false
	}
	digits, unit := value[:len(value)-1], value[len(value)-1]
	if digits[0] == '0' {
		return false
	}
	n := 0
	for _, char := range digits {
		if char < '0' || char > '9' {
			return false
		}
		n = n*10 + int(char-'0')
	}
	switch unit {
	case 'k':
		return n >= 1 && n <= maxStickyTableEntriesK
	case 'm':
		return n >= 1 && n <= maxStickyTableEntriesM
	}
	return false
}

// resolvePoolDistribution settles the two orthogonal 1.1.0 settings of a
// route with an explicit servers[] pool: balance_algorithm (server choice for
// a new client) and sticky_mode (client stickiness), plus their sub-fields
// and the common slowstart setting. balance_mode=failover ignores both axes
// and stores every field of this function empty/zero.
func resolvePoolDistribution(in *routeInput, out *RouteSpec, balanceMode string) error {
	if containsForbiddenControl(in.BalanceAlgorithm) || containsForbiddenControl(in.StickyMode) ||
		containsForbiddenControl(in.StickyTTL) || containsForbiddenControl(in.StickyHash) ||
		containsForbiddenControl(in.StickyTableEntries) || containsForbiddenControl(in.Slowstart) {
		return fmt.Errorf("route fields cannot contain control characters")
	}

	stickyIn := strings.ToLower(strings.TrimSpace(in.StickyMode))
	if stickyIn == StickyModeSNI {
		return fmt.Errorf(stickyModeSNIError)
	}
	balanceIn := strings.ToLower(strings.TrimSpace(in.BalanceAlgorithm))
	if !validBalanceAlgorithm(balanceIn) {
		return fmt.Errorf("balance_algorithm must be roundrobin, static-rr, random, leastconn or leastping")
	}

	var stickyMode string
	switch stickyIn {
	case "":
		if in.StickyEnabled || out.DNSPool || anyServerDNSPool(out.Servers) {
			stickyMode = StickyModeSource
		} else {
			stickyMode = StickyModeNone
		}
	case StickyModeNone, StickyModeSource, StickyModeSourceTable:
		stickyMode = stickyIn
	case StickyModeLeastConn:
		stickyMode = StickyModeNone
		if balanceIn == "" {
			balanceIn = BalanceAlgorithmLeastConn
		}
	case StickyModeRoundRobin:
		stickyMode = StickyModeNone
		if balanceIn == "" {
			balanceIn = BalanceAlgorithmRoundRobin
		}
	default:
		return fmt.Errorf("sticky_mode must be none, source or source_table")
	}
	if balanceIn == "" {
		if stickyMode == StickyModeSourceTable {
			balanceIn = BalanceAlgorithmLeastConn
		} else {
			balanceIn = BalanceAlgorithmRoundRobin
		}
	}
	out.BalanceAlgorithm = balanceIn

	if in.BalanceRandomDraws != 0 && (in.BalanceRandomDraws < minBalanceRandomDraws || in.BalanceRandomDraws > maxBalanceRandomDraws) {
		return fmt.Errorf("balance_random_draws must be between %d and %d", minBalanceRandomDraws, maxBalanceRandomDraws)
	}
	if out.BalanceAlgorithm == BalanceAlgorithmRandom {
		draws := in.BalanceRandomDraws
		if draws == 0 {
			draws = defaultBalanceRandomDraws
		}
		out.BalanceRandomDraws = draws
	} else {
		out.BalanceRandomDraws = 0
	}

	requested := in.LeastPingTolerance
	if in.BalanceTolerance != nil {
		if requested != nil && *requested != *in.BalanceTolerance {
			return fmt.Errorf("balance_tolerance and leastping_tolerance must be equal when both are sent")
		}
		requested = in.BalanceTolerance
	}
	tolerance := defaultLeastPingTolerance
	if requested != nil {
		tolerance = *requested
		if math.IsNaN(tolerance) || tolerance < 0 || tolerance > 1 {
			return fmt.Errorf("leastping_tolerance must be between 0 and 1")
		}
	}
	if in.LeastPingToleranceMS < 0 || in.LeastPingToleranceMS > maxLeastPingToleranceMS {
		return fmt.Errorf("leastping_tolerance_ms must be between 0 and %d", maxLeastPingToleranceMS)
	}
	if out.BalanceAlgorithm == BalanceAlgorithmLeastPing {
		out.LeastPingTolerance = tolerance
		out.LeastPingToleranceMS = in.LeastPingToleranceMS
		// leastping's effective latency is the HAProxy check_duration, so it
		// requires an active health check.
		out.HealthCheck = true
	} else if out.BalanceAlgorithm == BalanceAlgorithmLeastConn && stickyMode != StickyModeSource {
		// leastconn tolerance: servers whose connection load is within this
		// share of the least loaded one count as equally loaded (Agent
		// 1.1.1 runtime weights). Unset means 0 (plain HAProxy leastconn),
		// so existing leastconn routes render unchanged.
		out.LeastPingTolerance, out.LeastPingToleranceMS = 0, 0
		if requested != nil {
			out.LeastPingTolerance = math.Round(*requested*100) / 100
		}
	} else {
		out.LeastPingTolerance, out.LeastPingToleranceMS = 0, 0
	}

	hashType := strings.ToLower(strings.TrimSpace(in.StickyHash))
	if hashType != "" && hashType != "map-based" {
		return fmt.Errorf("sticky_hash must be '' (consistent) or map-based")
	}
	if in.StickyHashBalanceFactor != 0 && (in.StickyHashBalanceFactor < minStickyHashBalanceFactor || in.StickyHashBalanceFactor > maxStickyHashBalanceFactor) {
		return fmt.Errorf("sticky_hash_balance_factor must be 0 or between %d and %d", minStickyHashBalanceFactor, maxStickyHashBalanceFactor)
	}
	if in.StickyHashBalanceFactor != 0 && hashType == "map-based" {
		return fmt.Errorf("sticky_hash_balance_factor requires sticky_hash consistent (map-based has static weights)")
	}
	if in.StickyIPv6Prefix != 0 && (in.StickyIPv6Prefix < minStickyIPv6Prefix || in.StickyIPv6Prefix > maxStickyIPv6Prefix) {
		return fmt.Errorf("sticky_ipv6_prefix must be 0 or between %d and %d", minStickyIPv6Prefix, maxStickyIPv6Prefix)
	}
	tableEntries := strings.ToLower(strings.TrimSpace(in.StickyTableEntries))
	if !validStickyTableEntries(tableEntries) {
		return fmt.Errorf("sticky_table_entries must be '' or <n>k (1..%d) or <n>m (1..%d)", maxStickyTableEntriesK, maxStickyTableEntriesM)
	}
	ttl := strings.ToLower(strings.TrimSpace(in.StickyTTL))
	if ttl != "" {
		if _, ok := parseStickyTTL(ttl); !ok {
			return fmt.Errorf("sticky_ttl must be an HAProxy time between 1m and 7d (for example 15m, 1h, 7d)")
		}
	}

	switch stickyMode {
	case StickyModeSource:
		out.StickyHash = hashType
		out.StickyHashBalanceFactor = in.StickyHashBalanceFactor
		out.StickyIPv6Prefix = in.StickyIPv6Prefix
		out.StickyTableEntries, out.StickyTTL = "", ""
	case StickyModeSourceTable:
		if ttl == "" {
			ttl = defaultStickyTTL
		}
		out.StickyHash, out.StickyHashBalanceFactor = "", 0
		out.StickyIPv6Prefix = in.StickyIPv6Prefix
		out.StickyTableEntries, out.StickyTTL = tableEntries, ttl
	default:
		out.StickyHash, out.StickyHashBalanceFactor = "", 0
		out.StickyIPv6Prefix = 0
		out.StickyTableEntries, out.StickyTTL = "", ""
	}
	out.StickyMode = stickyMode
	out.StickyEnabled = stickyMode == StickyModeSource || stickyMode == StickyModeSourceTable
	// client_ipv6=false renders IPv4-only client tables; the IPv6 grouping
	// prefix has no meaning there and is cleared.
	if out.ClientIPv4Only {
		out.StickyIPv6Prefix = 0
	}

	if balanceMode == "pool" && anyServerIPWeightOverride(out.Servers) {
		staticWeights := out.BalanceAlgorithm == BalanceAlgorithmStaticRR ||
			(stickyMode == StickyModeSource && out.StickyHash == "map-based")
		if staticWeights {
			return fmt.Errorf("ip_weights need a dynamic-weight algorithm")
		}
	}

	slowstart, err := validateSlowstart(in.Slowstart, out.HealthCheck)
	if err != nil {
		return err
	}
	out.Slowstart = slowstart

	if balanceMode == "failover" {
		out.BalanceAlgorithm, out.BalanceRandomDraws = "", 0
		out.LeastPingTolerance, out.LeastPingToleranceMS = 0, 0
		out.StickyMode, out.StickyTTL, out.StickyEnabled = "", "", false
		out.StickyHash, out.StickyHashBalanceFactor = "", 0
		out.StickyTableEntries, out.StickyIPv6Prefix = "", 0
	}
	return nil
}

// anyServerIPWeightOverride reports whether any ip_weights entry sets a
// weight (a cost-only entry changes nothing outside leastping).
func anyServerIPWeightOverride(servers []RouteServerSpec) bool {
	for _, s := range servers {
		for _, w := range s.IPWeights {
			if w.Weight > 0 {
				return true
			}
		}
	}
	return false
}

func anyServerIPWeights(servers []RouteServerSpec) bool {
	for _, s := range servers {
		if len(s.IPWeights) > 0 {
			return true
		}
	}
	return false
}

// validateSlowstart validates the common pool-mode server ramp-up setting.
// ” means off; otherwise an HAProxy time between 1s and 10m, which requires
// an active health check (slowstart only applies after a server was seen
// down).
func validateSlowstart(raw string, healthCheck bool) (string, error) {
	if containsForbiddenControl(raw) {
		return "", fmt.Errorf("route fields cannot contain control characters")
	}
	value := strings.ToLower(strings.TrimSpace(raw))
	if value == "" {
		return "", nil
	}
	seconds, ok := parseHAProxyTimeSeconds(value)
	if !ok || seconds < minSlowstartSeconds || seconds > maxSlowstartSeconds {
		return "", fmt.Errorf("slowstart must be an HAProxy time between 1s and 10m")
	}
	if !healthCheck {
		return "", fmt.Errorf("slowstart requires health_check")
	}
	return value, nil
}

// parseHAProxyTimeSeconds accepts the same s/m/h/d subset as parseStickyTTL,
// without the upper bound (callers apply their own range).
func parseHAProxyTimeSeconds(value string) (int64, bool) {
	if len(value) < 2 || len(value) > 8 {
		return 0, false
	}
	unit := value[len(value)-1]
	digits := value[:len(value)-1]
	var n int64
	for _, char := range digits {
		if char < '0' || char > '9' {
			return 0, false
		}
		n = n*10 + int64(char-'0')
	}
	if digits[0] == '0' {
		return 0, false
	}
	switch unit {
	case 's':
		return n, true
	case 'm':
		return n * 60, true
	case 'h':
		return n * 3600, true
	case 'd':
		return n * 86400, true
	}
	return 0, false
}

func dnsPoolFragmentConflict(fragment string) bool {
	for _, line := range strings.Split(fragment, "\n") {
		fields := strings.Fields(strings.ToLower(line))
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "balance", "hash-type", "server", "server-template", "default-server":
			return true
		}
	}
	return false
}

func validateClientRateMbps(value *int64, field string) (*int64, error) {
	if value == nil {
		return nil, nil
	}
	if *value < 1 || *value > maxRouteClientRateMbps {
		return nil, fmt.Errorf("%s must be an integer between 1 and %d Mbps or null", field, maxRouteClientRateMbps)
	}
	rate := *value
	return &rate, nil
}

func validQuotaPeriod(value string) bool {
	switch value {
	case "hourly", "daily", "calendar_month", "monthly_from_creation":
		return true
	default:
		return false
	}
}

func normalizeDNSName(value string) (string, bool) {
	if containsForbiddenControl(value) {
		return "", false
	}
	value = strings.ToLower(strings.TrimSuffix(strings.TrimSpace(value), "."))
	return value, validDNSName(value)
}

func normalizeTargetHost(value string) (string, bool) {
	if containsForbiddenControl(value) {
		return "", false
	}
	value = strings.TrimSuffix(strings.TrimSpace(value), ".")
	if ip := net.ParseIP(value); ip != nil {
		return ip.String(), true
	}
	return normalizeDNSName(value)
}

func containsForbiddenControl(value string) bool {
	for _, char := range value {
		if char < 0x20 || char == 0x7f {
			return true
		}
	}
	return false
}

func validDNSName(value string) bool {
	if value == "" || len(value) > 253 || !utf8.ValidString(value) || strings.ContainsAny(value, "\r\n\t /:\\") {
		return false
	}
	labels := strings.Split(value, ".")
	for _, label := range labels {
		if len(label) < 1 || len(label) > 63 || label[0] == '-' || label[len(label)-1] == '-' {
			return false
		}
		for _, char := range label {
			if !((char >= 'a' && char <= 'z') || (char >= '0' && char <= '9') || char == '-') {
				return false
			}
		}
	}
	// A numeric last label is never a DNS name (RFC 3696 section 2: TLDs
	// are not all-numeric). Such strings are malformed IPv4 literals like
	// 1.2.3, 010.0.0.1 or 300.1.1.1 that libc may reinterpret (octal, short
	// forms) or that never resolve. inet_aton also accepts 0x hex parts.
	return !numericHostLabel(labels[len(labels)-1])
}

// numericHostLabel reports whether label is a decimal or 0x-hexadecimal
// number, i.e. something inet_aton would parse as an address part.
func numericHostLabel(label string) bool {
	if strings.Trim(label, "0123456789") == "" {
		return true
	}
	if hex, ok := strings.CutPrefix(label, "0x"); ok && hex != "" && strings.Trim(hex, "0123456789abcdef") == "" {
		return true
	}
	return false
}

func validUnixSocketPath(value string) bool {
	if len(value) < 2 || len(value) > MaxUnixSocketPathBytes || !utf8.ValidString(value) || !path.IsAbs(value) || path.Clean(value) != value {
		return false
	}
	for _, char := range value {
		if !((char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z') || (char >= '0' && char <= '9') || strings.ContainsRune("/._-", char)) {
			return false
		}
	}
	return true
}

// normalizeCustomFragment turns the legacy custom_fragment field into a
// canonical list of directives for this route's generated backend. HAProxy
// ignores indentation, so section headers have to be rejected after trimming.
// Backslashes are intentionally forbidden: HAProxy uses them for token and
// line escaping, which would make the route-level boundary ambiguous.
func normalizeCustomFragment(value string) (string, error) {
	if len(value) > MaxCustomFragmentBytes {
		return "", fmt.Errorf("custom_fragment must not exceed %d bytes", MaxCustomFragmentBytes)
	}
	if !utf8.ValidString(value) {
		return "", fmt.Errorf("custom_fragment must be valid UTF-8")
	}
	value = strings.ReplaceAll(value, "\r\n", "\n")
	for _, char := range value {
		if (char < 0x20 && char != '\n' && char != '\t') || char == 0x7f {
			return "", fmt.Errorf("custom_fragment contains a forbidden control character")
		}
	}
	if strings.ContainsRune(value, '\\') {
		return "", fmt.Errorf("custom_fragment cannot contain HAProxy escape characters")
	}

	lines := strings.Split(value, "\n")
	normalized := make([]string, 0, len(lines))
	blankPending := false
	for _, line := range lines {
		if len(line) > 512 {
			return "", fmt.Errorf("custom_fragment lines must not exceed 512 bytes")
		}
		directive := strings.TrimSpace(line)
		if directive == "" {
			if len(normalized) > 0 {
				blankPending = true
			}
			continue
		}
		fields := strings.Fields(strings.ToLower(directive))
		if len(fields) > 0 && forbiddenHAProxySection(fields[0]) {
			return "", fmt.Errorf("custom_fragment cannot declare HAProxy sections")
		}
		if blankPending {
			normalized = append(normalized, "")
			blankPending = false
		}
		normalized = append(normalized, "    "+directive)
	}
	result := strings.Join(normalized, "\n")
	if len(result) > MaxCustomFragmentBytes {
		return "", fmt.Errorf("custom_fragment must not exceed %d bytes after normalization", MaxCustomFragmentBytes)
	}
	return result, nil
}

func forbiddenHAProxySection(value string) bool {
	switch value {
	case "global", "defaults", "frontend", "backend", "listen", "peers", "resolvers", "userlist", "mailers", "cache", "program", "ring", "http-errors":
		return true
	default:
		return false
	}
}

// resolveRouteServers validates servers[] and settles the balance mode and
// per-server backup flags:
//   - balance_mode absent: explicit backup flags are kept (1.1.0-rc clients
//     send backup without balance_mode); any backup implies failover.
//   - balance_mode=failover: the first server in position order is primary,
//     every later server is a backup.
//   - balance_mode=pool: every server is primary.
//
// preferred_ip is only meaningful for the first (primary) server of a
// failover backend. A single DNS-pool server with preferred_ip and no
// balance_mode is implicitly failover, which is its only valid shape.
func resolveRouteServers(in []routeServerInput, rawMode string) ([]RouteServerSpec, string, error) {
	mode := strings.ToLower(strings.TrimSpace(rawMode))
	if mode != "" && mode != "pool" && mode != "failover" {
		return nil, "", fmt.Errorf("balance_mode must be pool or failover")
	}
	servers, err := validateRouteServers(in)
	if err != nil {
		return nil, "", err
	}
	if len(servers) == 0 {
		if mode == "" {
			mode = "pool"
		}
		return nil, mode, nil
	}
	switch mode {
	case "":
		mode = "pool"
		for _, s := range servers {
			if s.Backup {
				mode = "failover"
				break
			}
		}
		if mode == "pool" && len(servers) == 1 && servers[0].PreferredIP != "" {
			mode = "failover"
		}
	case "failover":
		for i := range servers {
			servers[i].Backup = i > 0
		}
	case "pool":
		for i := range servers {
			servers[i].Backup = false
		}
	}
	if servers[0].Backup {
		// Explicit legacy layouts may mark any server as backup; they still
		// need at least one active server.
		active := false
		for _, s := range servers {
			active = active || !s.Backup
		}
		if !active {
			return nil, "", fmt.Errorf("servers must include at least one non-backup server")
		}
	}
	for i, s := range servers {
		if s.PreferredIP != "" && (mode != "failover" || i != 0 || s.Backup) {
			return nil, "", fmt.Errorf("preferred_ip is only valid for the first server in failover mode")
		}
	}
	if mode == "failover" {
		// HAProxy has two tiers only. A DNS-pool reserve needs
		// "option allbackups" so that all resolved addresses share the load,
		// but that option makes every backup server active at once, which
		// would silently discard the priority order of any other reserve.
		dnsBackup := servers[0].DNSPool && servers[0].PreferredIP != ""
		backups := 0
		for _, s := range servers {
			if s.Backup {
				backups++
				dnsBackup = dnsBackup || s.DNSPool
			}
		}
		if servers[0].DNSPool && servers[0].PreferredIP != "" {
			backups++ // the DNS pool itself is the reserve of preferred_ip
		}
		if dnsBackup && backups > 1 {
			return nil, "", fmt.Errorf("in failover mode a DNS-pool reserve must be the only reserve: HAProxy uses all backup servers together when a DNS pool is a reserve")
		}
	}
	return servers, mode, nil
}

// validateRouteServers validates explicit multi-server definitions for a route.
// An empty slice is valid (renderer falls back to single-target mode).
// When non-empty: max MaxRouteServers, unique names and positions.
// DNSPool per-server: only allowed for domain (non-IP) TCP targets.
// PreferredIP: optional IP for a dns-pool server; placement is checked by
// resolveRouteServers. The result is sorted by position.
func validateRouteServers(servers []routeServerInput) ([]RouteServerSpec, error) {
	if len(servers) == 0 {
		return nil, nil
	}
	if len(servers) > MaxRouteServers {
		return nil, fmt.Errorf("servers must not exceed %d entries", MaxRouteServers)
	}
	seenNames := make(map[string]struct{}, len(servers))
	seenPositions := make(map[int]struct{}, len(servers))
	out := make([]RouteServerSpec, 0, len(servers))
	for i, srv := range servers {
		name := strings.TrimSpace(srv.Name)
		if !validRouteServerName(name) {
			return nil, fmt.Errorf("servers[%d].name must be 1-%d characters of A-Z, a-z, 0-9, _ or -", i, maxRouteServerNameLen)
		}
		if strings.HasSuffix(name, "_pref") {
			return nil, fmt.Errorf("servers[%d].name must not end with the reserved suffix _pref", i)
		}
		if _, exists := seenNames[name]; exists {
			return nil, fmt.Errorf("servers[%d].name %q is a duplicate", i, name)
		}
		seenNames[name] = struct{}{}
		pos := srv.Position
		if pos == 0 {
			// Position is optional in the API: default to array order.
			pos = i + 1
		}
		if pos < 1 || pos > MaxRouteServers {
			return nil, fmt.Errorf("servers[%d].position must be between 1 and %d", i, MaxRouteServers)
		}
		if _, exists := seenPositions[pos]; exists {
			return nil, fmt.Errorf("servers[%d].position %d is a duplicate", i, pos)
		}
		seenPositions[pos] = struct{}{}
		targetType := strings.ToLower(strings.TrimSpace(srv.TargetType))
		if targetType == "" {
			targetType = defaultRouteTargetType
		}
		spec := RouteServerSpec{Position: pos, Name: name, TargetType: targetType, Backup: srv.Backup}
		switch targetType {
		case "tcp":
			host, ok := normalizeTargetHost(srv.Host)
			if !ok || srv.Port < 1 || srv.Port > 65535 {
				return nil, fmt.Errorf("servers[%d] TCP entry requires a valid host and port", i)
			}
			spec.Host, spec.Port = host, srv.Port
			// dns_pool is only valid for domain (non-IP) TCP targets.
			if srv.DNSPool {
				if net.ParseIP(host) != nil {
					return nil, fmt.Errorf("servers[%d] dns_pool requires a DNS hostname, not an IP address", i)
				}
				spec.DNSPool = true
			}
		case "unix":
			socketPath := strings.TrimSpace(srv.UnixSocketPath)
			if !validUnixSocketPath(socketPath) {
				return nil, fmt.Errorf("servers[%d] unix_socket_path must be a canonical absolute Linux socket path up to %d bytes", i, MaxUnixSocketPathBytes)
			}
			spec.UnixSocketPath = socketPath
			if srv.DNSPool {
				return nil, fmt.Errorf("servers[%d] dns_pool is not valid for unix socket targets", i)
			}
		default:
			return nil, fmt.Errorf("servers[%d].target_type must be tcp or unix", i)
		}
		// Validate optional preferred_ip for dns_pool servers.
		if srv.PreferredIP != "" {
			if net.ParseIP(strings.TrimSpace(srv.PreferredIP)) == nil {
				return nil, fmt.Errorf("servers[%d].preferred_ip must be a valid IP address", i)
			}
			if !srv.DNSPool {
				return nil, fmt.Errorf("servers[%d].preferred_ip is only valid when dns_pool=true", i)
			}
			spec.PreferredIP = net.ParseIP(strings.TrimSpace(srv.PreferredIP)).String()
		}
		if srv.Weight != 0 && (srv.Weight < 1 || srv.Weight > 256) {
			return nil, fmt.Errorf("servers[%d].weight must be 0 or between 1 and 256", i)
		}
		spec.Weight = srv.Weight
		if srv.Cost != 0 && (srv.Cost < 0 || srv.Cost > 100) {
			return nil, fmt.Errorf("servers[%d].cost must be 0 or between 0 and 100", i)
		}
		spec.Cost = srv.Cost
		ipWeights, err := validateRouteServerIPWeights(srv.IPWeights, srv.DNSPool)
		if err != nil {
			return nil, fmt.Errorf("servers[%d].%s", i, err.Error())
		}
		spec.IPWeights = ipWeights
		out = append(out, spec)
	}
	// Template slots are named <name>_1..<name>_32; a static or other server
	// with such a name would duplicate a runtime name in the backend.
	for _, pool := range out {
		if !pool.DNSPool {
			continue
		}
		for _, other := range out {
			if suffix, found := strings.CutPrefix(other.Name, pool.Name+"_"); found && suffix != "" && strings.Trim(suffix, "0123456789") == "" {
				return nil, fmt.Errorf("servers name %q collides with DNS-pool server %q slot names", other.Name, pool.Name)
			}
		}
	}
	// Sort by position for deterministic rendering.
	sort.Slice(out, func(i, j int) bool { return out[i].Position < out[j].Position })
	return out, nil
}

const maxRouteServerIPWeights = 32

// validateRouteServerIPWeights validates the agent-applied runtime weight
// overrides of a DNS-pool template. Only meaningful for a dns_pool server;
// a non-empty list on any other server type is rejected.
func validateRouteServerIPWeights(values []RouteServerIPWeight, dnsPool bool) ([]RouteServerIPWeight, error) {
	if len(values) == 0 {
		return nil, nil
	}
	if !dnsPool {
		return nil, fmt.Errorf("ip_weights requires dns_pool=true")
	}
	if len(values) > maxRouteServerIPWeights {
		return nil, fmt.Errorf("ip_weights must not exceed %d entries", maxRouteServerIPWeights)
	}
	seen := make(map[string]struct{}, len(values))
	out := make([]RouteServerIPWeight, len(values))
	for i, w := range values {
		ip := net.ParseIP(strings.TrimSpace(w.IP))
		if ip == nil {
			return nil, fmt.Errorf("ip_weights[%d].ip must be a valid IP address", i)
		}
		normalized := ip.String()
		if _, exists := seen[normalized]; exists {
			return nil, fmt.Errorf("ip_weights[%d].ip %q is a duplicate", i, normalized)
		}
		seen[normalized] = struct{}{}
		if w.Weight < 0 || w.Weight > 256 {
			return nil, fmt.Errorf("ip_weights[%d].weight must be 0 (server weight) or between 1 and 256", i)
		}
		if math.IsNaN(w.Cost) || w.Cost < 0 || w.Cost > 100 {
			return nil, fmt.Errorf("ip_weights[%d].cost must be 0 (server cost) or greater than 0 and at most 100", i)
		}
		// numeric(6,2) semantics: the renderer prints two decimals.
		cost := math.Round(w.Cost*100) / 100
		if w.Cost > 0 && cost == 0 {
			return nil, fmt.Errorf("ip_weights[%d].cost must be at least 0.01", i)
		}
		if w.Weight == 0 && cost == 0 {
			return nil, fmt.Errorf("ip_weights[%d] must set weight, cost or both", i)
		}
		out[i] = RouteServerIPWeight{IP: normalized, Weight: w.Weight, Cost: cost}
	}
	return out, nil
}

// maxRouteServerNameLen leaves room for the generated "_pref" and "_NN"
// suffixes inside the 64-byte limit of route_servers.name.
const maxRouteServerNameLen = 58

// validRouteServerName restricts server names to a single HAProxy token, so
// a name can never inject keywords into the rendered server line.
func validRouteServerName(name string) bool {
	if len(name) < 1 || len(name) > maxRouteServerNameLen {
		return false
	}
	for _, char := range name {
		if !((char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z') || (char >= '0' && char <= '9') || char == '_' || char == '-') {
			return false
		}
	}
	return true
}

// validateAcceptProxyFrom parses and deduplicates a list of IPv4/IPv6
// addresses, CIDRs or DNS hostnames. IPs and CIDRs are canonicalised;
// hostnames are lower-cased without a trailing dot and stand for every A and
// AAAA address of the name, which the Node Agent resolves and keeps current
// at runtime. Returns a sorted, deduplicated slice.
func validateAcceptProxyFrom(values []string) ([]string, error) {
	if len(values) > MaxAcceptProxyFromEntries {
		return nil, fmt.Errorf("accept_proxy_from must not exceed %d entries", MaxAcceptProxyFromEntries)
	}
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	domains := 0
	for _, raw := range values {
		v := strings.TrimSpace(raw)
		if v == "" {
			continue
		}
		if containsForbiddenControl(v) {
			return nil, fmt.Errorf("accept_proxy_from entries cannot contain control characters")
		}
		// Accept plain IP or CIDR notation.
		if ip := net.ParseIP(v); ip != nil {
			v = ip.String()
		} else if normalized, err := normalizeAcceptProxyCIDR(v); err == nil {
			v = normalized
		} else if err != errNotCIDR {
			return nil, fmt.Errorf("accept_proxy_from entry %q %s", raw, err.Error())
		} else if host, ok := normalizeDNSName(v); ok {
			v = host
			if _, exists := seen[v]; !exists {
				domains++
			}
		} else {
			return nil, fmt.Errorf("accept_proxy_from entry %q is not a valid IP address, CIDR or hostname", raw)
		}
		if _, exists := seen[v]; exists {
			continue
		}
		seen[v] = struct{}{}
		out = append(out, v)
	}
	if domains > MaxAcceptProxyFromDomains {
		return nil, fmt.Errorf("accept_proxy_from must not contain more than %d hostnames", MaxAcceptProxyFromDomains)
	}
	sort.Strings(out)
	return out, nil
}

var errNotCIDR = fmt.Errorf("is not a valid CIDR")

// normalizeAcceptProxyCIDR canonicalises one CIDR. Only the literal
// 0.0.0.0/0 and ::/0 may mean "every source": net.IPNet.String() would turn
// an IPv4-mapped IPv6 prefix (::ffff:0:0/96) or any x.x.x.x/0 into
// 0.0.0.0/0 and silently switch the whole listener to an unconditional
// expect-proxy, so those forms are rejected instead.
func normalizeAcceptProxyCIDR(value string) (string, error) {
	ip, ipnet, err := net.ParseCIDR(value)
	if err != nil {
		return "", errNotCIDR
	}
	isIPv6Text := strings.Contains(value, ":")
	if isIPv6Text && ip.To4() != nil {
		return "", fmt.Errorf("is an IPv4-mapped IPv6 prefix; write the IPv4 CIDR instead")
	}
	if ones, _ := ipnet.Mask.Size(); ones == 0 {
		if !ip.IsUnspecified() {
			return "", fmt.Errorf("has prefix length 0 with a non-zero address; use exactly 0.0.0.0/0 or ::/0 to accept PROXY from all sources")
		}
		if isIPv6Text {
			return acceptProxyAllIPv6, nil
		}
		return acceptProxyAllIPv4, nil
	}
	return ipnet.String(), nil
}
